package pkginterface;

import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Charles
 */
public class Ihm extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public Ihm() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //System.setProperty("javax.net.ssl.trustStrore", "cacerts.jks");
                //System.setProperty("javax.net.ssl.keyStorePassword", "changeit");
                
                try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
                
                initComponents();
                miseEnPlace();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();
        donnees = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        donnees.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout donneesLayout = new javax.swing.GroupLayout(donnees);
        donnees.setLayout(donneesLayout);
        donneesLayout.setHorizontalGroup(
            donneesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        donneesLayout.setVerticalGroup(
            donneesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donnees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(donnees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public void miseEnPlace(){
        nextFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextFrameMouseClicked(evt);
            }
        });
        
        done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneMouseClicked(evt);
            }
        });
        
        /*Image img = null;
        try{
            img = ImageIO.read(new File("Frame"+frame+".jpg"));
        }
        catch(IOException e){
            System.out.println("Frame introuvable");
        }
        
        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/Frame0.jpg")));
        labelImage.setSize(img.getWidth(null), img.getWidth(null));*/
        labelImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageMouseClicked(evt);
            }
        });
        
        donnees.setLayout(new GridLayout(16,6));
        donnees.add(label2Dx);
        donnees.add(label2Dy);
        donnees.add(new javax.swing.JLabel());
        donnees.add(label3Dx);
        donnees.add(label3Dy);
        donnees.add(label3Dz);
        
        for(int j=1;j<=15;j++){
            if(j<=i){
            Ligne ligne = new Ligne();
            lignes.add(ligne);
            
            donnees.add(ligne.getField2Dx());
            donnees.add(ligne.getField2Dy());
            donnees.add(ligne.getVide());
            donnees.add(ligne.getField3Dx());
            donnees.add(ligne.getField3Dy());
            donnees.add(ligne.getField3Dz());
            }
            else if(j!=15){
                for(int k=0;k<6;k++){
                    donnees.add(new javax.swing.JLabel());
                }
            }
            if(j==15){
                for(int k=0;k<4;k++){
                    donnees.add(new javax.swing.JLabel());
                }
                donnees.add(nextFrame);
                donnees.add(done);
            }
            
        }
    }
    
    public void setImage(String chemin){
        Image img = null;
        try{
            img = ImageIO.read(new File(chemin));
        }
        catch(IOException e){
            System.out.println("Frame introuvable");
        }
        
        labelImage.setIcon(new javax.swing.ImageIcon(chemin));
        labelImage.setSize(img.getWidth(null), img.getWidth(null));
    }
    
    public void nextFrame(){
        for(Ligne ligne : lignes){
            ligne.getField2Dx().setText("");
            ligne.getField2Dy().setText("");
        }
        frame += 25;
        focus =0;
        new ChoixFrame(this).setVisible(true);
    }
    
    private void nextFrameMouseClicked(java.awt.event.MouseEvent evt){
        DonneesFrame.ajoutFrame(frame,lignes);
        nextFrame();
    }
    
    private void doneMouseClicked(java.awt.event.MouseEvent evt){
        DonneesFrame.ajoutFrame(frame,lignes);
        Enregistrement.Enregistrer(DonneesFrame.getDonnees());
        this.dispose();
        
    }
    
    private void labelImageMouseClicked(java.awt.event.MouseEvent evt){
        
        int x = evt.getX();
        int y = evt.getY();
        System.out.println("x = "+x+"\ny = "+y);
        //javax.swing.JTextField focus = (javax.swing.JTextField) this.getFocusOwner();
        lignes.get(focus).getField2Dx().setText(Integer.toString(x));
        lignes.get(focus).getField2Dy().setText(Integer.toString(y));
        if(focus<i-1){
            focus++;
        }
        else focus=0;
        lignes.get(focus).getField2Dx().requestFocus();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel donnees;
    private javax.swing.JLabel labelImage;
    private javax.swing.JPanel panelImage;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel label2Dx=new javax.swing.JLabel("X");
    private javax.swing.JLabel label2Dy=new javax.swing.JLabel("Y");
    private javax.swing.JLabel label3Dx=new javax.swing.JLabel("x");
    private javax.swing.JLabel label3Dy=new javax.swing.JLabel("y");
    private javax.swing.JLabel label3Dz=new javax.swing.JLabel("z");
    
    private javax.swing.JButton nextFrame=new javax.swing.JButton("+");
    private javax.swing.JButton done=new javax.swing.JButton("ok");
    
    private ArrayList<Ligne> lignes = new ArrayList<>();
    private int i = 8;
    private int frame = 0;
    private int focus=0;
    
}
